name: finance_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_database: ^10.5.4
  firebase_storage: ^11.7.4
  go_router: ^14.0.1
  intl: ^0.18.1
  floor: ^1.4.2
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  fl_chart: ^0.67.0
  flutter_svg: ^2.0.10+1
  url_launcher: ^6.2.6
  pay: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.4.9
  analyzer: ^5.13.0

flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/categories_icons/
    - assets/gpay.png
    - assets/user_placeholder.jpeg
    - assets/goal.svg

  fonts:
    - family: Archivo
      fonts:
        - asset: fonts/Archivo-Regular.ttf
        - asset: fonts/Archivo-Medium.ttf
          weight: 500
        - asset: fonts/Archivo-SemiBold.ttf
          weight: 600
        - asset: fonts/Archivo-Bold.ttf
          weight: 700
        - asset: fonts/Archivo-Light.ttf
          weight: 300
